workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.3
      xcode: latest
      java: 17.0.0  # Use Java 17 for AGP 8.1.0
      groups:
        - google_credentials # <-- For Google Play publishing (if needed)
      vars:
        PACKAGE_NAME: "com.example.app_md" # <-- Use your app's actual bundle ID
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages and upgrade dependencies
        script: |
          flutter pub get
          flutter pub upgrade --major-versions
      - name: Fix compile SDK issue
        script: |
          echo "compileSdkVersion = 34" > "$CM_BUILD_DIR/android/app/build.gradle.new"
          sed -e 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' "$CM_BUILD_DIR/android/app/build.gradle" > "$CM_BUILD_DIR/android/app/build.gradle.new"
          mv "$CM_BUILD_DIR/android/app/build.gradle.new" "$CM_BUILD_DIR/android/app/build.gradle"
      - name: Build Debug APK with Flutter
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.3
      xcode: latest
      groups:
        - app_store_credentials # <-- For App Store publishing (if needed)
      vars:
        BUNDLE_ID: "com.example.app_md" # <-- Use your app's actual bundle ID
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build unsigned iOS app for debug
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log 